namespace Chainborn.Licensing.Abstractions;

/// <summary>
/// Represents a portable license proof generated by the customer.
/// </summary>
public record LicenseProof(
    byte[] ProofBytes,
    byte[] VerificationKeyBytes,
    string ProductId,
    ProofChallenge Challenge,
    IReadOnlyDictionary<string, string>? Metadata = null);
